# theme="monokai_pro_spectrum"
# theme="dracula"
theme="custom_tokyonight"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# https://github.com/helix-editor/helix/pull/5934#issuecomment-1445040945
[editor.lsp]
display-inlay-hints = true
